name: My First Workflow

on: [push]


jobs:
    first_jobs:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4   

        - name: LIST & READ FILES 
          run: |
           echo "My first github action job"
           ls -ltra
           cat README.md 

        - name: GENERATTE ASCII ARTWORK  
          run: cowsay -f dragon "Run for cover, i am a Dragon....RAWR" >> gragon.txt  
          
        # - name: List Files
        #   run: ls
          
        # - name: Read Filfe
        #   run: cat README.md
